apiVersion: apps/v1
kind: Deployment
metadata:
  name: game
  labels:
    app: game
spec:
  replicas: 1
  selector:
    matchLabels:
      app: game
  template:
    metadata:
      labels:
        app: game
    spec:
      containers:
        - name: game
          image: 10.0.2.12:5000/exp7/exp7-game:v1
          imagePullPolicy: IfNotPresent
          command: ["/app/game"]
          env:
            - name: GAME_ADDR
              value: "0.0.0.0:8081"
          ports:
            - name: http
              containerPort: 8081
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8081
            initialDelaySeconds: 1
            periodSeconds: 3
---
apiVersion: v1
kind: Service
metadata:
  name: game-service
spec:
  type: ClusterIP
  selector:
    app: game
  ports:
    - name: http
      port: 8081
      targetPort: 8081
