apiVersion: v1
kind: Service
metadata:
  name: lab4-redis
  namespace: lab4
spec:
  ports:
  - port: 6379
  selector:
    app: lab4-redis
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: lab4-redis
  namespace: lab4
spec:
  serviceName: "lab4-redis"
  replicas: 1
  selector:
    matchLabels:
      app: lab4-redis
  template:
    metadata:
      labels:
        app: lab4-redis
    spec:
      containers:
      - name: redis
        image: redis:7-alpine
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 6379
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "256Mi"
