apiVersion: v1
kind: Service
metadata:
  name: game-service-external
spec:
  type: NodePort
  selector:
    app: game
  ports:
    - name: http
      port: 8081
      targetPort: 8081
      nodePort: 30080
