apiVersion: apps/v1
kind: Deployment
metadata:
  name: storage-deployment
  labels:
    app: storage
spec:
  replicas: 1
  selector:
    matchLabels:
      app: storage
  template:
    metadata:
      labels:
        app: storage
    spec:
      containers:
        - name: storage
          # Image pushed to local registry (example)
          image: 10.0.2.12:5000/exp_aliyun_k8s/game-storage:v1
          imagePullPolicy: IfNotPresent
          env:
            - name: STORAGE_ADDR
              value: "0.0.0.0:8082"
            - name: STORAGE_LOG_PATH
              value: "/app/data/players.log"
          volumeMounts:
            - name: data
              mountPath: /app/data
          ports:
            - containerPort: 8082
      volumes:
        - name: data
          emptyDir: {}
