apiVersion: v1
kind: Service
metadata:
  name: battleworld-gateway
  namespace: battleworld
  labels:
    app: battleworld
spec:
  type: NodePort
  selector:
    app: battleworld
  ports:
    - port: 9310
      targetPort: 9310
      nodePort: 30310
      name: gateway
