apiVersion: v1
kind: Service
metadata:
  name: lab3-gateway
  namespace: lab3-split
spec:
  type: LoadBalancer
  selector:
    app: lab3-gateway
  ports:
    - name: tcp-gateway
      port: 9310
      targetPort: 9310
