apiVersion: apps/v1
kind: Deployment
metadata:
  name: lab3-map-green
  namespace: lab3-split
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lab3-map-green
  template:
    metadata:
      labels:
        app: lab3-map-green
    spec:
      serviceAccountName: lab3-runner
      containers:
        - name: map
          image: ccr.ccs.tencentyun.com/lab4/map:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: LAB3_MAP_ID
              value: "green"
            - name: LAB3_NODE_ID
              value: "map-green"
            - name: LAB3_MAP_LISTEN_ADDR
              value: ":9400"
          ports:
            - containerPort: 9400
              name: http
          readinessProbe:
            httpGet:
              path: /healthz
              port: 9400
            initialDelaySeconds: 3
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /healthz
              port: 9400
            initialDelaySeconds: 10
            periodSeconds: 10
