apiVersion: apps/v1
kind: Deployment
metadata:
  name: lab4-coordinator
  namespace: lab4
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lab4-coordinator
  template:
    metadata:
      labels:
        app: lab4-coordinator
      annotations:
        controller.kubernetes.io/pod-deletion-cost: "-1000"
        lab4/active-players: "0"
        lab4/draining: "false"
    spec:
      serviceAccountName: lab4-runner
      terminationGracePeriodSeconds: 240
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: kubernetes.io/hostname
          whenUnsatisfiable: ScheduleAnyway
          labelSelector:
            matchLabels:
              app: lab4-coordinator
      containers:
        - name: coordinator
          image: lab4/coordinator:local
          imagePullPolicy: IfNotPresent
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: LAB4_NAMESPACE
              value: "lab4"
            - name: LAB4_STATE_BACKEND
              value: "redis"
            - name: LAB4_REDIS_ADDR
              value: "lab4-redis:6379"
            - name: LAB4_REDIS_PREFIX
              value: "lab4"
            - name: LAB4_PRESTOP_DELAY
              value: "8s"
            - name: LAB4_COORDINATOR_DRAIN_TIMEOUT
              value: "180s"
            - name: LAB4_COMPONENT
              value: "coordinator"
            - name: LAB4_COORDINATOR_ADDR
              value: ":9320"
            - name: LAB4_GREEN_URL
              value: "http://lab4-map-green:9400"
            - name: LAB4_CAVE_URL
              value: "http://lab4-map-cave:9400"
            - name: LAB4_RUINS_URL
              value: "http://lab4-map-ruins:9400"
            - name: LAB4_GREEN_NODE_ID
              value: "map-green"
            - name: LAB4_CAVE_NODE_ID
              value: "map-cave"
            - name: LAB4_RUINS_NODE_ID
              value: "map-ruins"
          ports:
            - containerPort: 9320
              name: http
          readinessProbe:
            httpGet:
              path: /readyz
              port: 9320
            initialDelaySeconds: 3
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /healthz
              port: 9320
            initialDelaySeconds: 10
            periodSeconds: 10
          lifecycle:
            preStop:
              httpGet:
                path: /drain
                port: 9320
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 500m
              memory: 256Mi
