apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: lab4-gateway
  namespace: lab4
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: lab4-gateway
  minReplicas: 1
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 60
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: lab4-coordinator
  namespace: lab4
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: lab4-coordinator
  minReplicas: 1
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 60
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: lab4-map-green
  namespace: lab4
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: lab4-map-green
  minReplicas: 1
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 60
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: lab4-map-cave
  namespace: lab4
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: lab4-map-cave
  minReplicas: 1
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 60
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: lab4-map-ruins
  namespace: lab4
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: lab4-map-ruins
  minReplicas: 1
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 60
