apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: lab4-redis
  namespace: lab4
spec:
  serviceName: lab4-redis
  replicas: 1
  selector:
    matchLabels:
      app: lab4-redis
  template:
    metadata:
      labels:
        app: lab4-redis
    spec:
      terminationGracePeriodSeconds: 60
      containers:
        - name: redis
          image: redis:7-alpine
          imagePullPolicy: IfNotPresent
          args:
            - redis-server
            - --appendonly
            - "yes"
            - --save
            - "60"
            - "1"
            - --dir
            - /data
          ports:
            - containerPort: 6379
              name: redis
          readinessProbe:
            tcpSocket:
              port: 6379
            initialDelaySeconds: 3
            periodSeconds: 5
          livenessProbe:
            tcpSocket:
              port: 6379
            initialDelaySeconds: 10
            periodSeconds: 10
          resources:
            requests:
              cpu: 50m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
          volumeMounts:
            - name: data
              mountPath: /data
      volumes:
        - name: data
          hostPath:
            path: /var/lib/lab4/redis
            type: DirectoryOrCreate
