apiVersion: apps/v1
kind: Deployment
metadata:
  name: lab4-gateway
  namespace: lab4
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lab4-gateway
  template:
    metadata:
      labels:
        app: lab4-gateway
    spec:
      serviceAccountName: lab4-runner
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: kubernetes.io/hostname
          whenUnsatisfiable: ScheduleAnyway
          labelSelector:
            matchLabels:
              app: lab4-gateway
      containers:
        - name: gateway
          image: lab4/gateway:local
          imagePullPolicy: IfNotPresent
          env:
            - name: LAB4_GATEWAY_ADDR
              value: "0.0.0.0:9310"
            - name: LAB4_COORDINATOR_URL
              value: "http://lab4-coordinator:9320"
          ports:
            - containerPort: 9310
              name: tcp-gateway
          readinessProbe:
            tcpSocket:
              port: 9310
            initialDelaySeconds: 3
            periodSeconds: 5
          livenessProbe:
            tcpSocket:
              port: 9310
            initialDelaySeconds: 10
            periodSeconds: 10
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 300m
              memory: 128Mi
