apiVersion: v1
kind: Service
metadata:
  name: lab4-gateway
  namespace: lab4
spec:
  type: NodePort
  selector:
    app: lab4-gateway
  ports:
    - name: tcp-gateway
      port: 9310
      targetPort: 9310
      nodePort: 30910
